# This is a basic workflow to help you get started with Actions

name: CI-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ BigInteger ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: preprocess
        run: |
            sudo apt-get -y install valgrind
            chmod -R +x .github/scripts
      - name: Build
        run: make work_test
      - name: Memory_Test
        run: make memory_test
      - name: Allocator_tests
        run: make allocs_test
      - name: Code_Style_test
        run: make code_style_test
